# .github/workflows/deploy-cloudflare.yml
# Updated workflow using wrangler-action (recommended 2024/2025)

name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=inspire-motivate-coaching

      - name: Deployment success
        run: |
          echo "✅ Deployment complete!"
          echo "🌐 Your site should be live at: https://inspire-motivate-coaching.pages.dev"
