# .github/workflows/deploy-cloudflare.yml
# Ultra-simple workflow for static HTML sites

name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: inspire-motivate-coaching
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Deployment success
        run: echo "✅ Your website has been deployed successfully!"
